// **********************************************************************
// This file was generated by a TAF parser!
// TAF version " 9.1.1_20221103111450 " by TAF Team.
// Generated from `File`
// **********************************************************************
/* eslint-disable */
var assert    = require('assert');
var TafStream = require('@taf/taf-stream');
if (TafStream.JceStruct == undefined) {
    TafStream.JceStruct = function() {
        this._jce_double_precision_ = -1;
    }
    TafStream.JceStruct.prototype.setPrecision = function(d) {
        if ((d == -1) || (d >= 0 && d <= 15)) {
            this._jce_double_precision_ = d;
            return true;
        }
        return false;
    }
    TafStream.JceStruct.prototype.resetPrecision = function() { this._jce_double_precision_ = -1;}
    TafStream.JceStruct.prototype.hasSetPrecision = function() { return (this._jce_double_precision_ >= 0 && this._jce_double_precision_ <= 15);}
    TafStream.JceStruct.prototype.getPrecision = function() { return this._jce_double_precision_; }
}
var COMM = COMM || {};
module.exports.COMM = COMM;
COMM.RETCODE = {
    SUCC : 0,
    BUCKET_NOT_EXIST : -101,
    FILE_NOT_EXIST : -102,
    AUTH_ERROR : -103,
    UNKOWN : -104,
};
COMM.RETCODE.etos = function(enm) {
    switch(enm){
        case 0 : return 'SUCC';
        case -101 : return 'BUCKET_NOT_EXIST';
        case -102 : return 'FILE_NOT_EXIST';
        case -103 : return 'AUTH_ERROR';
        case -104 : return 'UNKOWN';
    }
    return undefined;
};
COMM.RETCODE.stoe = function(enm) {
    switch(enm){
        case 'SUCC' : return 0;
        case 'BUCKET_NOT_EXIST' : return -101;
        case 'FILE_NOT_EXIST' : return -102;
        case 'AUTH_ERROR' : return -103;
        case 'UNKOWN' : return -104;
    }
    return undefined;
};
COMM.RETCODE._write = function(os, tag, val) { return os.writeInt32(tag, val); }
COMM.RETCODE._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
COMM.HeadersInfo = function() {
    this.sContentType = "";
    this.sContentEncoding = "";
    this.sContentDisposition = "";
    this.sContentLanguage = "";
    this.sCacheControl = "";
    this.sExpires = "";
    this.sLastModified = "";
    this.sContentLength = "";
    this._classname = "COMM.HeadersInfo";
};
COMM.HeadersInfo.prototype = new TafStream.JceStruct();
COMM.HeadersInfo._classname = "COMM.HeadersInfo";
COMM.HeadersInfo._write = function (os, tag, value) { os.writeStruct(tag, value); }
COMM.HeadersInfo._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
COMM.HeadersInfo._readFrom = function (is) {
    if (is.readResumePrecision == undefined) {
        is.readResumePrecision = function() {
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new COMM.HeadersInfo();
    tmp.sContentType = is.readString(0, false, "");
    tmp.sContentEncoding = is.readString(1, false, "");
    tmp.sContentDisposition = is.readString(2, false, "");
    tmp.sContentLanguage = is.readString(3, false, "");
    tmp.sCacheControl = is.readString(4, false, "");
    tmp.sExpires = is.readString(5, false, "");
    tmp.sLastModified = is.readString(6, false, "");
    tmp.sContentLength = is.readString(7, false, "");
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
COMM.HeadersInfo.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if(this.sContentType != undefined && this.sContentType != "") {
        os.writeString(0, this.sContentType);
    }
    if(this.sContentEncoding != undefined && this.sContentEncoding != "") {
        os.writeString(1, this.sContentEncoding);
    }
    if(this.sContentDisposition != undefined && this.sContentDisposition != "") {
        os.writeString(2, this.sContentDisposition);
    }
    if(this.sContentLanguage != undefined && this.sContentLanguage != "") {
        os.writeString(3, this.sContentLanguage);
    }
    if(this.sCacheControl != undefined && this.sCacheControl != "") {
        os.writeString(4, this.sCacheControl);
    }
    if(this.sExpires != undefined && this.sExpires != "") {
        os.writeString(5, this.sExpires);
    }
    if(this.sLastModified != undefined && this.sLastModified != "") {
        os.writeString(6, this.sLastModified);
    }
    if(this.sContentLength != undefined && this.sContentLength != "") {
        os.writeString(7, this.sContentLength);
    }
    os.resumePrecision && os.resumePrecision();
};
COMM.HeadersInfo.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
COMM.HeadersInfo.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
COMM.HeadersInfo.prototype.toObject = function() {
    var tmp = {};
    tmp.sContentType = this.sContentType;
    tmp.sContentEncoding = this.sContentEncoding;
    tmp.sContentDisposition = this.sContentDisposition;
    tmp.sContentLanguage = this.sContentLanguage;
    tmp.sCacheControl = this.sCacheControl;
    tmp.sExpires = this.sExpires;
    tmp.sLastModified = this.sLastModified;
    tmp.sContentLength = this.sContentLength;
    return tmp;
}
COMM.HeadersInfo.prototype.readFromObject = function(json) {
    !json.hasOwnProperty("sContentType") || (this.sContentType = json.sContentType);
    !json.hasOwnProperty("sContentEncoding") || (this.sContentEncoding = json.sContentEncoding);
    !json.hasOwnProperty("sContentDisposition") || (this.sContentDisposition = json.sContentDisposition);
    !json.hasOwnProperty("sContentLanguage") || (this.sContentLanguage = json.sContentLanguage);
    !json.hasOwnProperty("sCacheControl") || (this.sCacheControl = json.sCacheControl);
    !json.hasOwnProperty("sExpires") || (this.sExpires = json.sExpires);
    !json.hasOwnProperty("sLastModified") || (this.sLastModified = json.sLastModified);
    !json.hasOwnProperty("sContentLength") || (this.sContentLength = json.sContentLength);
}
COMM.HeadersInfo.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
COMM.HeadersInfo.new = function () {
    return new COMM.HeadersInfo();
}
COMM.HeadersInfo.create = function (is) {
    return COMM.HeadersInfo._readFrom(is);
}
COMM.UploadFileReq = function() {
    this.sBusId = "";
    this.sBucket = "";
    this.sPath = "";
    this.vContent = new TafStream.BinBuffer;
    this.sOrgFileName = "";
    this.iRename = 0;
    this.headersInfo = new COMM.HeadersInfo;
    this.customHeaders = new TafStream.Map(TafStream.String, TafStream.String);
    this.updateCDN = false;
    this._classname = "COMM.UploadFileReq";
};
COMM.UploadFileReq.prototype = new TafStream.JceStruct();
COMM.UploadFileReq._classname = "COMM.UploadFileReq";
COMM.UploadFileReq._write = function (os, tag, value) { os.writeStruct(tag, value); }
COMM.UploadFileReq._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
COMM.UploadFileReq._readFrom = function (is) {
    if (is.readResumePrecision == undefined) {
        is.readResumePrecision = function() {
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new COMM.UploadFileReq();
    tmp.sBusId = is.readString(0, false, "");
    tmp.sBucket = is.readString(1, false, "");
    tmp.sPath = is.readString(2, false, "");
    tmp.vContent = is.readBytes(3, false, TafStream.BinBuffer);
    tmp.sOrgFileName = is.readString(4, false, "");
    tmp.iRename = is.readInt32(5, false, 0);
    tmp.headersInfo = is.readStruct(6, false, COMM.HeadersInfo);
    tmp.customHeaders = is.readMap(7, false, TafStream.Map(TafStream.String, TafStream.String));
    tmp.updateCDN = is.readBoolean(8, false, false);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
COMM.UploadFileReq.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if(this.sBusId != undefined && this.sBusId != "") {
        os.writeString(0, this.sBusId);
    }
    if(this.sBucket != undefined && this.sBucket != "") {
        os.writeString(1, this.sBucket);
    }
    if(this.sPath != undefined && this.sPath != "") {
        os.writeString(2, this.sPath);
    }
    if(this.vContent != undefined && this.vContent.length > 0) {
        os.writeBytes(3, this.vContent);
    }
    if(this.sOrgFileName != undefined && this.sOrgFileName != "") {
        os.writeString(4, this.sOrgFileName);
    }
    if(this.iRename != undefined && this.iRename != 0) {
        os.writeInt32(5, this.iRename);
    }
    os.writeStruct(6, this.headersInfo);
    if(this.customHeaders != undefined && this.customHeaders.size() > 0) {
        os.writeMap(7, this.customHeaders);
    }
    if(this.updateCDN != undefined && this.updateCDN != false) {
        os.writeBoolean(8, this.updateCDN);
    }
    os.resumePrecision && os.resumePrecision();
};
COMM.UploadFileReq.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
COMM.UploadFileReq.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
COMM.UploadFileReq.prototype.toObject = function() {
    var tmp = {};
    tmp.sBusId = this.sBusId;
    tmp.sBucket = this.sBucket;
    tmp.sPath = this.sPath;
    tmp.vContent = this.vContent.toObject() ;
    tmp.sOrgFileName = this.sOrgFileName;
    tmp.iRename = this.iRename;
    tmp.headersInfo = this.headersInfo.toObject() ;
    tmp.customHeaders = this.customHeaders.toObject() ;
    tmp.updateCDN = this.updateCDN;
    return tmp;
}
COMM.UploadFileReq.prototype.readFromObject = function(json) {
    !json.hasOwnProperty("sBusId") || (this.sBusId = json.sBusId);
    !json.hasOwnProperty("sBucket") || (this.sBucket = json.sBucket);
    !json.hasOwnProperty("sPath") || (this.sPath = json.sPath);
    !json.hasOwnProperty("vContent") || (this.vContent.readFromObject(json.vContent));
    !json.hasOwnProperty("sOrgFileName") || (this.sOrgFileName = json.sOrgFileName);
    !json.hasOwnProperty("iRename") || (this.iRename = json.iRename);
    !json.hasOwnProperty("headersInfo") || (this.headersInfo.readFromObject(json.headersInfo));
    !json.hasOwnProperty("customHeaders") || (this.customHeaders.readFromObject(json.customHeaders));
    !json.hasOwnProperty("updateCDN") || (this.updateCDN = json.updateCDN);
}
COMM.UploadFileReq.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
COMM.UploadFileReq.new = function () {
    return new COMM.UploadFileReq();
}
COMM.UploadFileReq.create = function (is) {
    return COMM.UploadFileReq._readFrom(is);
}
COMM.UploadFileRsp = function() {
    this.iRet = COMM.RETCODE.SUCC;
    this.sObjPath = "";
    this._classname = "COMM.UploadFileRsp";
};
COMM.UploadFileRsp.prototype = new TafStream.JceStruct();
COMM.UploadFileRsp._classname = "COMM.UploadFileRsp";
COMM.UploadFileRsp._write = function (os, tag, value) { os.writeStruct(tag, value); }
COMM.UploadFileRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
COMM.UploadFileRsp._readFrom = function (is) {
    if (is.readResumePrecision == undefined) {
        is.readResumePrecision = function() {
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new COMM.UploadFileRsp();
    tmp.iRet = is.readInt32(0, false, COMM.RETCODE.SUCC);
    tmp.sObjPath = is.readString(1, false, "");
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
COMM.UploadFileRsp.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if(this.iRet != undefined && this.iRet != COMM.RETCODE.SUCC) {
        os.writeInt32(0, this.iRet);
    }
    if(this.sObjPath != undefined && this.sObjPath != "") {
        os.writeString(1, this.sObjPath);
    }
    os.resumePrecision && os.resumePrecision();
};
COMM.UploadFileRsp.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
COMM.UploadFileRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
COMM.UploadFileRsp.prototype.toObject = function() {
    var tmp = {};
    tmp.iRet = this.iRet;
    tmp.sObjPath = this.sObjPath;
    return tmp;
}
COMM.UploadFileRsp.prototype.readFromObject = function(json) {
    !json.hasOwnProperty("iRet") || (this.iRet = json.iRet);
    !json.hasOwnProperty("sObjPath") || (this.sObjPath = json.sObjPath);
}
COMM.UploadFileRsp.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
COMM.UploadFileRsp.new = function () {
    return new COMM.UploadFileRsp();
}
COMM.UploadFileRsp.create = function (is) {
    return COMM.UploadFileRsp._readFrom(is);
}
COMM.GetFileReq = function() {
    this.sBusId = "";
    this.sBucket = "";
    this.sObjPath = "";
    this._classname = "COMM.GetFileReq";
};
COMM.GetFileReq.prototype = new TafStream.JceStruct();
COMM.GetFileReq._classname = "COMM.GetFileReq";
COMM.GetFileReq._write = function (os, tag, value) { os.writeStruct(tag, value); }
COMM.GetFileReq._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
COMM.GetFileReq._readFrom = function (is) {
    if (is.readResumePrecision == undefined) {
        is.readResumePrecision = function() {
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new COMM.GetFileReq();
    tmp.sBusId = is.readString(0, false, "");
    tmp.sBucket = is.readString(1, false, "");
    tmp.sObjPath = is.readString(2, false, "");
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
COMM.GetFileReq.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if(this.sBusId != undefined && this.sBusId != "") {
        os.writeString(0, this.sBusId);
    }
    if(this.sBucket != undefined && this.sBucket != "") {
        os.writeString(1, this.sBucket);
    }
    if(this.sObjPath != undefined && this.sObjPath != "") {
        os.writeString(2, this.sObjPath);
    }
    os.resumePrecision && os.resumePrecision();
};
COMM.GetFileReq.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
COMM.GetFileReq.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
COMM.GetFileReq.prototype.toObject = function() {
    var tmp = {};
    tmp.sBusId = this.sBusId;
    tmp.sBucket = this.sBucket;
    tmp.sObjPath = this.sObjPath;
    return tmp;
}
COMM.GetFileReq.prototype.readFromObject = function(json) {
    !json.hasOwnProperty("sBusId") || (this.sBusId = json.sBusId);
    !json.hasOwnProperty("sBucket") || (this.sBucket = json.sBucket);
    !json.hasOwnProperty("sObjPath") || (this.sObjPath = json.sObjPath);
}
COMM.GetFileReq.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
COMM.GetFileReq.new = function () {
    return new COMM.GetFileReq();
}
COMM.GetFileReq.create = function (is) {
    return COMM.GetFileReq._readFrom(is);
}
COMM.GetFileRsp = function() {
    this.iRet = COMM.RETCODE.SUCC;
    this.vContent = new TafStream.BinBuffer;
    this._classname = "COMM.GetFileRsp";
};
COMM.GetFileRsp.prototype = new TafStream.JceStruct();
COMM.GetFileRsp._classname = "COMM.GetFileRsp";
COMM.GetFileRsp._write = function (os, tag, value) { os.writeStruct(tag, value); }
COMM.GetFileRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
COMM.GetFileRsp._readFrom = function (is) {
    if (is.readResumePrecision == undefined) {
        is.readResumePrecision = function() {
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new COMM.GetFileRsp();
    tmp.iRet = is.readInt32(0, false, COMM.RETCODE.SUCC);
    tmp.vContent = is.readBytes(1, false, TafStream.BinBuffer);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
COMM.GetFileRsp.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if(this.iRet != undefined && this.iRet != COMM.RETCODE.SUCC) {
        os.writeInt32(0, this.iRet);
    }
    if(this.vContent != undefined && this.vContent.length > 0) {
        os.writeBytes(1, this.vContent);
    }
    os.resumePrecision && os.resumePrecision();
};
COMM.GetFileRsp.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
COMM.GetFileRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
COMM.GetFileRsp.prototype.toObject = function() {
    var tmp = {};
    tmp.iRet = this.iRet;
    tmp.vContent = this.vContent.toObject() ;
    return tmp;
}
COMM.GetFileRsp.prototype.readFromObject = function(json) {
    !json.hasOwnProperty("iRet") || (this.iRet = json.iRet);
    !json.hasOwnProperty("vContent") || (this.vContent.readFromObject(json.vContent));
}
COMM.GetFileRsp.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
COMM.GetFileRsp.new = function () {
    return new COMM.GetFileRsp();
}
COMM.GetFileRsp.create = function (is) {
    return COMM.GetFileRsp._readFrom(is);
}
COMM.delFileReq = function() {
    this.sBusId = "";
    this.sBucket = "";
    this.sObjPath = "";
    this._classname = "COMM.delFileReq";
};
COMM.delFileReq.prototype = new TafStream.JceStruct();
COMM.delFileReq._classname = "COMM.delFileReq";
COMM.delFileReq._write = function (os, tag, value) { os.writeStruct(tag, value); }
COMM.delFileReq._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
COMM.delFileReq._readFrom = function (is) {
    if (is.readResumePrecision == undefined) {
        is.readResumePrecision = function() {
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new COMM.delFileReq();
    tmp.sBusId = is.readString(0, false, "");
    tmp.sBucket = is.readString(1, false, "");
    tmp.sObjPath = is.readString(2, false, "");
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
COMM.delFileReq.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if(this.sBusId != undefined && this.sBusId != "") {
        os.writeString(0, this.sBusId);
    }
    if(this.sBucket != undefined && this.sBucket != "") {
        os.writeString(1, this.sBucket);
    }
    if(this.sObjPath != undefined && this.sObjPath != "") {
        os.writeString(2, this.sObjPath);
    }
    os.resumePrecision && os.resumePrecision();
};
COMM.delFileReq.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
COMM.delFileReq.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
COMM.delFileReq.prototype.toObject = function() {
    var tmp = {};
    tmp.sBusId = this.sBusId;
    tmp.sBucket = this.sBucket;
    tmp.sObjPath = this.sObjPath;
    return tmp;
}
COMM.delFileReq.prototype.readFromObject = function(json) {
    !json.hasOwnProperty("sBusId") || (this.sBusId = json.sBusId);
    !json.hasOwnProperty("sBucket") || (this.sBucket = json.sBucket);
    !json.hasOwnProperty("sObjPath") || (this.sObjPath = json.sObjPath);
}
COMM.delFileReq.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
COMM.delFileReq.new = function () {
    return new COMM.delFileReq();
}
COMM.delFileReq.create = function (is) {
    return COMM.delFileReq._readFrom(is);
}
COMM.delFileRsp = function() {
    this.iRet = COMM.RETCODE.SUCC;
    this._classname = "COMM.delFileRsp";
};
COMM.delFileRsp.prototype = new TafStream.JceStruct();
COMM.delFileRsp._classname = "COMM.delFileRsp";
COMM.delFileRsp._write = function (os, tag, value) { os.writeStruct(tag, value); }
COMM.delFileRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
COMM.delFileRsp._readFrom = function (is) {
    if (is.readResumePrecision == undefined) {
        is.readResumePrecision = function() {
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new COMM.delFileRsp();
    tmp.iRet = is.readInt32(0, false, COMM.RETCODE.SUCC);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
COMM.delFileRsp.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if(this.iRet != undefined && this.iRet != COMM.RETCODE.SUCC) {
        os.writeInt32(0, this.iRet);
    }
    os.resumePrecision && os.resumePrecision();
};
COMM.delFileRsp.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
COMM.delFileRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
COMM.delFileRsp.prototype.toObject = function() {
    var tmp = {};
    tmp.iRet = this.iRet;
    return tmp;
}
COMM.delFileRsp.prototype.readFromObject = function(json) {
    !json.hasOwnProperty("iRet") || (this.iRet = json.iRet);
}
COMM.delFileRsp.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
COMM.delFileRsp.new = function () {
    return new COMM.delFileRsp();
}
COMM.delFileRsp.create = function (is) {
    return COMM.delFileRsp._readFrom(is);
}
